package life.majiang.community.model;

import java.util.ArrayList;
import java.util.List;

public class AttentionExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table attention
     *
     * @mbg.generated Tue Mar 31 13:07:27 CST 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table attention
     *
     * @mbg.generated Tue Mar 31 13:07:27 CST 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table attention
     *
     * @mbg.generated Tue Mar 31 13:07:27 CST 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attention
     *
     * @mbg.generated Tue Mar 31 13:07:27 CST 2020
     */
    public AttentionExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attention
     *
     * @mbg.generated Tue Mar 31 13:07:27 CST 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attention
     *
     * @mbg.generated Tue Mar 31 13:07:27 CST 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attention
     *
     * @mbg.generated Tue Mar 31 13:07:27 CST 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attention
     *
     * @mbg.generated Tue Mar 31 13:07:27 CST 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attention
     *
     * @mbg.generated Tue Mar 31 13:07:27 CST 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attention
     *
     * @mbg.generated Tue Mar 31 13:07:27 CST 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attention
     *
     * @mbg.generated Tue Mar 31 13:07:27 CST 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attention
     *
     * @mbg.generated Tue Mar 31 13:07:27 CST 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attention
     *
     * @mbg.generated Tue Mar 31 13:07:27 CST 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attention
     *
     * @mbg.generated Tue Mar 31 13:07:27 CST 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table attention
     *
     * @mbg.generated Tue Mar 31 13:07:27 CST 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andAttentionUserIsNull() {
            addCriterion("attention_user is null");
            return (Criteria) this;
        }

        public Criteria andAttentionUserIsNotNull() {
            addCriterion("attention_user is not null");
            return (Criteria) this;
        }

        public Criteria andAttentionUserEqualTo(Long value) {
            addCriterion("attention_user =", value, "attentionUser");
            return (Criteria) this;
        }

        public Criteria andAttentionUserNotEqualTo(Long value) {
            addCriterion("attention_user <>", value, "attentionUser");
            return (Criteria) this;
        }

        public Criteria andAttentionUserGreaterThan(Long value) {
            addCriterion("attention_user >", value, "attentionUser");
            return (Criteria) this;
        }

        public Criteria andAttentionUserGreaterThanOrEqualTo(Long value) {
            addCriterion("attention_user >=", value, "attentionUser");
            return (Criteria) this;
        }

        public Criteria andAttentionUserLessThan(Long value) {
            addCriterion("attention_user <", value, "attentionUser");
            return (Criteria) this;
        }

        public Criteria andAttentionUserLessThanOrEqualTo(Long value) {
            addCriterion("attention_user <=", value, "attentionUser");
            return (Criteria) this;
        }

        public Criteria andAttentionUserIn(List<Long> values) {
            addCriterion("attention_user in", values, "attentionUser");
            return (Criteria) this;
        }

        public Criteria andAttentionUserNotIn(List<Long> values) {
            addCriterion("attention_user not in", values, "attentionUser");
            return (Criteria) this;
        }

        public Criteria andAttentionUserBetween(Long value1, Long value2) {
            addCriterion("attention_user between", value1, value2, "attentionUser");
            return (Criteria) this;
        }

        public Criteria andAttentionUserNotBetween(Long value1, Long value2) {
            addCriterion("attention_user not between", value1, value2, "attentionUser");
            return (Criteria) this;
        }

        public Criteria andAttentionedUserIsNull() {
            addCriterion("attentioned_user is null");
            return (Criteria) this;
        }

        public Criteria andAttentionedUserIsNotNull() {
            addCriterion("attentioned_user is not null");
            return (Criteria) this;
        }

        public Criteria andAttentionedUserEqualTo(Long value) {
            addCriterion("attentioned_user =", value, "attentionedUser");
            return (Criteria) this;
        }

        public Criteria andAttentionedUserNotEqualTo(Long value) {
            addCriterion("attentioned_user <>", value, "attentionedUser");
            return (Criteria) this;
        }

        public Criteria andAttentionedUserGreaterThan(Long value) {
            addCriterion("attentioned_user >", value, "attentionedUser");
            return (Criteria) this;
        }

        public Criteria andAttentionedUserGreaterThanOrEqualTo(Long value) {
            addCriterion("attentioned_user >=", value, "attentionedUser");
            return (Criteria) this;
        }

        public Criteria andAttentionedUserLessThan(Long value) {
            addCriterion("attentioned_user <", value, "attentionedUser");
            return (Criteria) this;
        }

        public Criteria andAttentionedUserLessThanOrEqualTo(Long value) {
            addCriterion("attentioned_user <=", value, "attentionedUser");
            return (Criteria) this;
        }

        public Criteria andAttentionedUserIn(List<Long> values) {
            addCriterion("attentioned_user in", values, "attentionedUser");
            return (Criteria) this;
        }

        public Criteria andAttentionedUserNotIn(List<Long> values) {
            addCriterion("attentioned_user not in", values, "attentionedUser");
            return (Criteria) this;
        }

        public Criteria andAttentionedUserBetween(Long value1, Long value2) {
            addCriterion("attentioned_user between", value1, value2, "attentionedUser");
            return (Criteria) this;
        }

        public Criteria andAttentionedUserNotBetween(Long value1, Long value2) {
            addCriterion("attentioned_user not between", value1, value2, "attentionedUser");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table attention
     *
     * @mbg.generated do_not_delete_during_merge Tue Mar 31 13:07:27 CST 2020
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table attention
     *
     * @mbg.generated Tue Mar 31 13:07:27 CST 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}