package life.majiang.community.model;

public class Attention {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attention.id
     *
     * @mbg.generated Tue Mar 31 13:07:27 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attention.attention_user
     *
     * @mbg.generated Tue Mar 31 13:07:27 CST 2020
     */
    private Long attentionUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attention.attentioned_user
     *
     * @mbg.generated Tue Mar 31 13:07:27 CST 2020
     */
    private Long attentionedUser;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attention.id
     *
     * @return the value of attention.id
     *
     * @mbg.generated Tue Mar 31 13:07:27 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attention.id
     *
     * @param id the value for attention.id
     *
     * @mbg.generated Tue Mar 31 13:07:27 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attention.attention_user
     *
     * @return the value of attention.attention_user
     *
     * @mbg.generated Tue Mar 31 13:07:27 CST 2020
     */
    public Long getAttentionUser() {
        return attentionUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attention.attention_user
     *
     * @param attentionUser the value for attention.attention_user
     *
     * @mbg.generated Tue Mar 31 13:07:27 CST 2020
     */
    public void setAttentionUser(Long attentionUser) {
        this.attentionUser = attentionUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attention.attentioned_user
     *
     * @return the value of attention.attentioned_user
     *
     * @mbg.generated Tue Mar 31 13:07:27 CST 2020
     */
    public Long getAttentionedUser() {
        return attentionedUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attention.attentioned_user
     *
     * @param attentionedUser the value for attention.attentioned_user
     *
     * @mbg.generated Tue Mar 31 13:07:27 CST 2020
     */
    public void setAttentionedUser(Long attentionedUser) {
        this.attentionedUser = attentionedUser;
    }
}