package life.majiang.community.model;

public class Collect {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collect.id
     *
     * @mbg.generated Tue Mar 31 13:07:27 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collect.user
     *
     * @mbg.generated Tue Mar 31 13:07:27 CST 2020
     */
    private Long user;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collect.question
     *
     * @mbg.generated Tue Mar 31 13:07:27 CST 2020
     */
    private Long question;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collect.time
     *
     * @mbg.generated Tue Mar 31 13:07:27 CST 2020
     */
    private Long time;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collect.id
     *
     * @return the value of collect.id
     *
     * @mbg.generated Tue Mar 31 13:07:27 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collect.id
     *
     * @param id the value for collect.id
     *
     * @mbg.generated Tue Mar 31 13:07:27 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collect.user
     *
     * @return the value of collect.user
     *
     * @mbg.generated Tue Mar 31 13:07:27 CST 2020
     */
    public Long getUser() {
        return user;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collect.user
     *
     * @param user the value for collect.user
     *
     * @mbg.generated Tue Mar 31 13:07:27 CST 2020
     */
    public void setUser(Long user) {
        this.user = user;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collect.question
     *
     * @return the value of collect.question
     *
     * @mbg.generated Tue Mar 31 13:07:27 CST 2020
     */
    public Long getQuestion() {
        return question;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collect.question
     *
     * @param question the value for collect.question
     *
     * @mbg.generated Tue Mar 31 13:07:27 CST 2020
     */
    public void setQuestion(Long question) {
        this.question = question;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collect.time
     *
     * @return the value of collect.time
     *
     * @mbg.generated Tue Mar 31 13:07:27 CST 2020
     */
    public Long getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collect.time
     *
     * @param time the value for collect.time
     *
     * @mbg.generated Tue Mar 31 13:07:27 CST 2020
     */
    public void setTime(Long time) {
        this.time = time;
    }
}