package life.majiang.community.model;

public class Contact {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contact.id
     *
     * @mbg.generated Tue Mar 31 13:07:27 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contact.user1
     *
     * @mbg.generated Tue Mar 31 13:07:27 CST 2020
     */
    private Long user1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contact.user2
     *
     * @mbg.generated Tue Mar 31 13:07:27 CST 2020
     */
    private Long user2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contact.gmt
     *
     * @mbg.generated Tue Mar 31 13:07:27 CST 2020
     */
    private Long gmt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contact.id
     *
     * @return the value of contact.id
     *
     * @mbg.generated Tue Mar 31 13:07:27 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contact.id
     *
     * @param id the value for contact.id
     *
     * @mbg.generated Tue Mar 31 13:07:27 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contact.user1
     *
     * @return the value of contact.user1
     *
     * @mbg.generated Tue Mar 31 13:07:27 CST 2020
     */
    public Long getUser1() {
        return user1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contact.user1
     *
     * @param user1 the value for contact.user1
     *
     * @mbg.generated Tue Mar 31 13:07:27 CST 2020
     */
    public void setUser1(Long user1) {
        this.user1 = user1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contact.user2
     *
     * @return the value of contact.user2
     *
     * @mbg.generated Tue Mar 31 13:07:27 CST 2020
     */
    public Long getUser2() {
        return user2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contact.user2
     *
     * @param user2 the value for contact.user2
     *
     * @mbg.generated Tue Mar 31 13:07:27 CST 2020
     */
    public void setUser2(Long user2) {
        this.user2 = user2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contact.gmt
     *
     * @return the value of contact.gmt
     *
     * @mbg.generated Tue Mar 31 13:07:27 CST 2020
     */
    public Long getGmt() {
        return gmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contact.gmt
     *
     * @param gmt the value for contact.gmt
     *
     * @mbg.generated Tue Mar 31 13:07:27 CST 2020
     */
    public void setGmt(Long gmt) {
        this.gmt = gmt;
    }
}